version: "3.9"
services:
  api:
    env_file:
      - .env
    build:
      context: ./
    volumes:
      - ./:/nicasource-video-platform
      - /nicasource-video-platform/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:${DB_PORT}'
volumes:
  postgres:
    driver: local
